stages:
  - bot # comes from translations/generator job

include:
  - project: 'translations/generator'
    ref: master
    file: '/jobs/sync-crowdin.gitlab-ci.yml'

  - project: 'translations/generator'
    ref: master
    file: '/jobs/commit-locales.gitlab-ci.yml'


# --- Translation related tasks ---
i18n-sync-crowdin:
  variables:
      I18N_SYNC_CROWDIN_PROJECT: 'apple-mail'
  extends: .i18n-sync-crowdin-shared-apple

i18n-commit-locales:
  variables:
      I18N_COMMIT_CROWDIN_PROJECT: 'apple-mail'
  extends: .i18n-commit-locales-shared-apple2

